opt_in_rules:
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fatal_error_message
  - first_where
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - legacy_random
  - let_var_whitespace
  - number_separator
  - operator_usage_whitespace
  - private_action
  - private_outlet
  - redundant_type_annotation
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - unused_private_declaration
disabled_rules:
  - type_body_length
  - file_length
  - function_body_length
  - function_parameter_count
  - nesting
force_cast: warning
force_try:
  severity: warning
type_name:
  min_length: 2
  max_length:
    warning: 40
    error: 50
identifier_name:
  min_length: 2
  excluded:
    - id
    - URL
    - x
    - y
    - i
excluded:
  - Pods